=== Colptha/xml-education-services/validation/instructors.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="instructors">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="instructor" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="instructor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="firstName" />
        <xs:element ref="lastName" />
        <xs:element ref="salary" />
      </xs:sequence>
      <xs:attribute ref="iID" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="firstName" type="xs:string" />
  <xs:element name="lastName" type="xs:string" />
  <xs:element name="salary" type="xs:positiveInteger" />

  <xs:attribute name="iID">
     <xs:simpleType>
        <xs:restriction base="xs:string">
           <xs:pattern value="I\d{2}" />
        </xs:restriction>
     </xs:simpleType>
  </xs:attribute>

</xs:schema>

=== Colptha/xml-education-services/xml-source/instructors.xml
<?xml version="1.0" encoding="UTF-8" ?>

<instructors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="../validation/instructors.xsd">
  <instructor iID="I01">
    <firstName>Johnny</firstName>
    <lastName>Cash</lastName>
    <salary>50000</salary>
  </instructor>
  <instructor iID="I02">
    <firstName>Tony</firstName>
    <lastName>Thomas</lastName>
    <salary>45000</salary>
  </instructor>
  <instructor iID="I03">
    <firstName>Chris</firstName>
    <lastName>Lee</lastName>
    <salary>42000</salary>
  </instructor>
  <instructor iID="I04">
    <firstName>Greg</firstName>
    <lastName>Beale</lastName>
    <salary>55000</salary>
  </instructor>
  <instructor iID="I05">
    <firstName>Don</firstName>
    <lastName>Carson</lastName>
    <salary>61000</salary>
  </instructor>
</instructors>
