=== Colptha/xml-education-services/validation/students.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="student" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="student">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="firstName" />
        <xs:element ref="lastName" />
        <xs:element ref="courses" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="firstName" type="xs:string" />
  <xs:element name="lastName" type="xs:string" />

  <xs:element name="courses">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="course" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="course">
    <xs:complexType>
      <xs:attribute ref="cID" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:attribute name="cID">
    <xs:simpleType>
       <xs:restriction base="xs:string">
          <xs:pattern value="[a-z]+\d{3}" />
       </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

</xs:schema>

=== Colptha/xml-education-services/xml-source/students.xml
<?xml version="1.0" encoding="UTF-8" ?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="../validation/students.xsd">
  <student>
    <firstName>Phillip</firstName>
    <lastName>Yohe</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring001" />
      <course cID="git003" />
      <course cID="xml001" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>Laurel</firstName>
    <lastName>Gorton</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring001" />
      <course cID="git003" />
      <course cID="xml001" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>Bethann</firstName>
    <lastName>Upham</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring001" />
      <course cID="git003" />
      <course cID="xml001" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>Daphne</firstName>
    <lastName>Minter</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring001" />
      <course cID="git003" />
      <course cID="xml001" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>Charlesetta</firstName>
    <lastName>Smalls</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring001" />
      <course cID="git003" />
      <course cID="xml001" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>Alline</firstName>
    <lastName>Brodersen</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring001" />
      <course cID="git003" />
      <course cID="xml001" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>Gretta</firstName>
    <lastName>Carignan</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring001" />
      <course cID="git003" />
      <course cID="xml001" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>April</firstName>
    <lastName>Lane</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring001" />
      <course cID="git003" />
      <course cID="xml001" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>Barrie</firstName>
    <lastName>Forehand</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring001" />
      <course cID="git003" />
      <course cID="xml001" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>Enda</firstName>
    <lastName>Tippit</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring001" />
      <course cID="git003" />
      <course cID="xml001" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>Hermelinda</firstName>
    <lastName>Sanders</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring001" />
      <course cID="git003" />
      <course cID="xml001" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>Palmer</firstName>
    <lastName>Mager</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring001" />
      <course cID="git003" />
      <course cID="xml001" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>Valarie</firstName>
    <lastName>Rakow</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring002" />
      <course cID="git003" />
      <course cID="xml001" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>Rodney</firstName>
    <lastName>Coakley</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring002" />
      <course cID="git003" />
      <course cID="xml001" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>Gennie</firstName>
    <lastName>Sartwell</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring002" />
      <course cID="git003" />
      <course cID="xml001" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>Heide</firstName>
    <lastName>Grunwald</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring002" />
      <course cID="git003" />
      <course cID="xml002" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>Alec</firstName>
    <lastName>Shue</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring002" />
      <course cID="git003" />
      <course cID="xml002" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>Geoffrey</firstName>
    <lastName>Egerton</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring002" />
      <course cID="git003" />
      <course cID="xml002" />
      <course cID="hiber001" />
    </courses>
  </student>
  <student>
    <firstName>Shaquana</firstName>
    <lastName>Haney</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring002" />
      <course cID="git003" />
      <course cID="xml002" />
      <course cID="hiber002" />
    </courses>
  </student>
  <student>
    <firstName>Silvia</firstName>
    <lastName>Prokop</lastName>
    <courses>
      <course cID="java001" />
      <course cID="spring002" />
      <course cID="git003" />
      <course cID="xml002" />
      <course cID="hiber002" />
    </courses>
  </student>
  <student>
    <firstName>Ciera</firstName>
    <lastName>Corn</lastName>
    <courses>
      <course cID="java002" />
      <course cID="spring002" />
      <course cID="git003" />
      <course cID="xml002" />
      <course cID="hiber002" />
    </courses>
  </student>
  <student>
    <firstName>Deon</firstName>
    <lastName>Debose</lastName>
    <courses>
      <course cID="java002" />
      <course cID="spring002" />
      <course cID="git003" />
      <course cID="xml002" />
      <course cID="hiber002" />
    </courses>
  </student>
  <student>
    <firstName>Kendal</firstName>
    <lastName>Jessie</lastName>
    <courses>
      <course cID="java002" />
      <course cID="spring002" />
      <course cID="git003" />
      <course cID="xml002" />
      <course cID="hiber002" />
    </courses>
  </student>
  <student>
    <firstName>Lacie</firstName>
    <lastName>Cavins</lastName>
    <courses>
      <course cID="java002" />
      <course cID="spring002" />
      <course cID="git003" />
      <course cID="xml002" />
      <course cID="hiber002" />
    </courses>
  </student>
  <student>
    <firstName>Tien</firstName>
    <lastName>Dennard</lastName>
    <courses>
      <course cID="java002" />
      <course cID="spring002" />
      <course cID="git003" />
      <course cID="xml002" />
      <course cID="hiber002" />
    </courses>
  </student>
  <student>
    <firstName>Marlon</firstName>
    <lastName>Ericksen</lastName>
    <courses>
      <course cID="java002" />
      <course cID="spring002" />
      <course cID="git003" />
      <course cID="xml002" />
      <course cID="hiber002" />
    </courses>
  </student>
  <student>
    <firstName>Brandee</firstName>
    <lastName>Craghead</lastName>
    <courses>
      <course cID="java002" />
      <course cID="spring003" />
      <course cID="git003" />
      <course cID="xml002" />
      <course cID="hiber002" />
    </courses>
  </student>
  <student>
    <firstName>Warner</firstName>
    <lastName>Killen</lastName>
    <courses>
      <course cID="java002" />
      <course cID="spring003" />
      <course cID="git003" />
      <course cID="xml002" />
      <course cID="hiber002" />
    </courses>
  </student>
  <student>
    <firstName>Shae</firstName>
    <lastName>Rozier</lastName>
    <courses>
      <course cID="java002" />
      <course cID="spring003" />
      <course cID="git003" />
      <course cID="xml002" />
      <course cID="hiber002" />
    </courses>
  </student>
  <student>
    <firstName>Cathy</firstName>
    <lastName>Cutting</lastName>
    <courses>
      <course cID="java002" />
      <course cID="spring003" />
      <course cID="git003" />
      <course cID="xml002" />
      <course cID="hiber002" />
    </courses>
  </student>
  <student>
    <firstName>Hayley</firstName>
    <lastName>Macdowell</lastName>
    <courses>
      <course cID="java002" />
      <course cID="spring003" />
      <course cID="git003" />
      <course cID="xml002" />
      <course cID="hiber002" />
    </courses>
  </student>
  <student>
    <firstName>Willie</firstName>
    <lastName>Wand</lastName>
    <courses>
      <course cID="java002" />
      <course cID="spring003" />
      <course cID="git003" />
      <course cID="xml003" />
      <course cID="hiber002" />
    </courses>
  </student>
  <student>
    <firstName>Gabrielle</firstName>
    <lastName>Zander</lastName>
    <courses>
      <course cID="java002" />
      <course cID="spring003" />
      <course cID="git003" />
      <course cID="xml003" />
      <course cID="hiber002" />
    </courses>
  </student>
  <student>
    <firstName>Jamee</firstName>
    <lastName>Winward</lastName>
    <courses>
      <course cID="java002" />
      <course cID="spring003" />
      <course cID="git003" />
      <course cID="xml003" />
      <course cID="hiber002" />
    </courses>
  </student>
  <student>
    <firstName>Gigi</firstName>
    <lastName>Storey</lastName>
    <courses>
      <course cID="java002" />
      <course cID="spring003" />
      <course cID="git003" />
      <course cID="xml003" />
      <course cID="hiber002" />
    </courses>
  </student>
  <student>
    <firstName>Dania</firstName>
    <lastName>Criado</lastName>
    <courses>
      <course cID="java002" />
